version: '3.8'

services:
  web:
    build: .
    image: php:8.2-apache
    container_name: lamp_web
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: lamp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exemple
      MYSQL_USER: usuari
      MYSQL_PASSWORD: contrasenya
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: usuari
      PMA_PASSWORD: contrasenya
    ports:
      - "8081:80"
